// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaCl11hhkRkTo733RQ00edfe4zZnzBMt8',
    appId: '1:830121591799:web:0148116d6e9fd44182a4f2',
    messagingSenderId: '830121591799',
    projectId: 'chat-b2595',
    authDomain: 'chat-b2595.firebaseapp.com',
    storageBucket: 'chat-b2595.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBskyGbm7ja8oh_d0d0PeuUhUXMiPrmlLI',
    appId: '1:830121591799:android:2d295eedbfdea08382a4f2',
    messagingSenderId: '830121591799',
    projectId: 'chat-b2595',
    storageBucket: 'chat-b2595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxvDCKJPYUOcHYRhoDI9vJY6XLqo9DNYs',
    appId: '1:830121591799:ios:64aafd36f502dddb82a4f2',
    messagingSenderId: '830121591799',
    projectId: 'chat-b2595',
    storageBucket: 'chat-b2595.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxvDCKJPYUOcHYRhoDI9vJY6XLqo9DNYs',
    appId: '1:830121591799:ios:64aafd36f502dddb82a4f2',
    messagingSenderId: '830121591799',
    projectId: 'chat-b2595',
    storageBucket: 'chat-b2595.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaCl11hhkRkTo733RQ00edfe4zZnzBMt8',
    appId: '1:830121591799:web:a24778377423b48282a4f2',
    messagingSenderId: '830121591799',
    projectId: 'chat-b2595',
    authDomain: 'chat-b2595.firebaseapp.com',
    storageBucket: 'chat-b2595.appspot.com',
  );

}